FROM node:20-alpine

WORKDIR /app

COPY package*.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . ./

ENV NODE_ENV=test

CMD sh -c "echo 'Auth service test container is up! Waiting for you to run tests...' && tail -f /dev/null"




