FROM node:20-alpine

WORKDIR /app

COPY package*.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . ./

RUN npx prisma generate

ENV NODE_ENV=development

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && yarn dev"]

