name: Auth Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - services/auth-service/**
      - .github/workflows/auth-ci.yml
  push:
    branches:
      - main
    paths:
      - services/auth-service/**
      - .github/workflows/auth-ci.yml

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build lint image
        run: docker build --target lint -t auth-service:lint ./services/auth-service

      - name: Run lint in container
        run: docker run --rm auth-service:lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build unit test image
        run: docker build --target unit -t auth-service:unit ./services/auth-service

      - name: Run unit test in container
        run: docker run --rm auth-service:unit

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_AUTH }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_AUTH }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_AUTH }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build E2E test image
        run: docker build --target e2e -t auth-service:e2e ./services/auth-service

      - name: Run E@E test in container
        run: |
          docker run --rm \
            -e DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER_AUTH }}:${{ secrets.POSTGRES_PASSWORD_AUTH }}@postgres:5432/${{ secrets.POSTGRES_DB_AUTH }}?schema=public \
            -e JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }} \
            -e JWT_ACCESS_TOKEN_TIME=${{ secrets.JWT_ACCESS_TOKEN_TIME }} \
            -e JWT_REFRESH_TOKEN_SECRET=${{ secrets.JWT_REFRESH_TOKEN_SECRET }} \
            -e JWT_REFRESH_TOKEN_TIME=${{ secrets.JWT_REFRESH_TOKEN_TIME }} \
            -e REDIS_USE_TLS_AUTH=${{ secrets.REDIS_USE_TLS_AUTH }} \
            -e REDIS_URL_AUTH=${{ secrets.REDIS_URL_AUTH }} \
            auth-service:e2e

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build project image
        run: docker build --target build -t auth-service:build ./services/auth-service

  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -target production \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./services/auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
