name: Auth Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - services/auth-service/**
      - .github/workflows/auth-ci.yml
  push:
    branches:
      - main
    paths:
      - services/auth-service/**
      - .github/workflows/auth-ci.yml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run lint
        run: |
          chmod +x ./services/auth-service/scripts/lint.sh
          ./services/auth-service/scripts/lint.sh

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run unit test
        run: |
          chmod +x ./services/auth-service/scripts/unit-test.sh
          ./services/auth-service/scripts/unit-test.sh

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env.test
        run: |
          echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER_AUTH }}:${{ secrets.POSTGRES_PASSWORD_AUTH }}@postgres:5432/${{ secrets.POSTGRES_DB_AUTH }}?schema=public" > ./services/auth-service/.env.test
          echo "JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }}" >> ./services/auth-service/.env.test
          echo "JWT_ACCESS_TOKEN_TIME=${{ secrets.JWT_ACCESS_TOKEN_TIME }}" >> ./services/auth-service/.env.test
          echo "JWT_REFRESH_TOKEN_SECRET=${{ secrets.JWT_REFRESH_TOKEN_SECRET }}" >> ./services/auth-service/.env.test
          echo "JWT_REFRESH_TOKEN_TIME=${{ secrets.JWT_REFRESH_TOKEN_TIME }}" >> ./services/auth-service/.env.test
          echo "REDIS_USE_TLS_AUTH=${{ secrets.REDIS_USE_TLS_AUTH }}" >> ./services/auth-service/.env.test
          echo "REDIS_URL_AUTH=${{ secrets.REDIS_URL_AUTH }}" >> ./services/auth-service/.env.test

      - name: Run E2E tests with docker-compose
        working-directory: ./services/auth-service
        run: |
          chmod +x ./scripts/e2e-test.sh
          ./scripts/e2e-test.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run build
        run: |
          chmod +x ./services/auth-service/scripts/build.sh
          ./services/auth-service/scripts/build.sh

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run docker build & push
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          chmod +x ./services/auth-service/scripts/docker-build-push.sh
          ./services/auth-service/scripts/docker-build-push.sh
